### ISSUE TITLE
首诊大项中，提交检查仅覆盖入选标准

### ISSUE THREAD

**Issue by Yudatech** [Yudatech/yuda-ecrf#105]
首诊仅填写入选标准页，其余项为空，提交检查仍显示其他项目完成。排除标准提交逻辑正确，无需变动，特此说明一下

**Comment by Yudatech** [comment]
手术中也有相关情况。要不除了手术的选填项“肛门外监测导管长度-若使用DMHC(cm)”和“中吻合口完整性压力-若使用DMHC(mbar)”都改为必填项，否则不能提交

**Comment by Yudatech** [comment]
排除标准提交逻辑正确，无需变动，特此说明一下

**Comment by bohua** [comment]
可否在提交检查页中增加每项未填写项的数量，如 首诊   -  23 项未填写，同时其状态为未完成
