### ISSUE TITLE
每日 自动备份 数据

### ISSUE THREAD

**Issue by bohua** [Yudatech/yuda-ecrf#141]
1. 后台自动运行
2. 导出并备份数据库
3. 每日备份命名规则： backup_2017_10_03_10:20 （备份文件格式随意）
4. 能保证可以事后回档或者挽救曾经备份过的数据即可

**Comment by sunwenyuan** [comment]
crontab job 每天两点42分执行
备份到/tmp/db_backup
文件夹名 111017  (月日年)
