### ISSUE TITLE
AE和SAEcommit后检测问题

### ISSUE THREAD

**Issue by suzhang2020** [Yudatech/yuda-ecrf#183]
1. TS账号登陆，密码Test
2. 进入TS0006
3. 已知在Surgery中，最下面勾选了Adverse Event；已知在POD4-6中，也需要填写Adverse Event
4. 在Adverse Event中分别添加surgery和POD4-6中对应的adverse event，其中来源为surgery的那个AE，勾选页面底部SAE选项，正常弹出提示需要完成SAE report
5. 在Serious adverse event中添加SAE，initiation report填写所有选项
6. 在serious adverse event中再添加一个SAE，summary report，填写所有选项
7. 点击commit，系统检测后认为Adverse event中，勾选SAE的那条AE未完成
8. 点击commit，系统检测后认为SAE那条也未完成，可是已经在步骤5和6中填写了所有选项

![Screen Shot 2020-09-08 at 20 58 22](https://user-images.githubusercontent.com/69921295/92517646-48eeca80-f217-11ea-9097-b30b7faa811c.png)

**Comment by sunwenyuan** [comment]
这个可能有些误会，SAE的来源要选定AE才能识别，如果选了Other是没有办法识别的

**Comment by suzhang2020** [comment]
可是SAE的来源选项里没有相应的AE来源，只能选other

**Comment by sunwenyuan** [comment]
已经加上了

**Comment by suzhang2020** [comment]
谢谢！我试了一下，目前TS账号登陆，TS0006病例，有一条SAE（来源为AE中test的Summary report）始终在commit后过不去。把该SAE来源换成Other也过不去。
![Screen Shot 2020-09-09 at 15 36 48](https://user-images.githubusercontent.com/69921295/92607070-f0213f80-f2b3-11ea-8673-a814297317a4.png)

另外想请问：
针对同一个来源的AE，如果要添加SAE，只能添加一条SAE么？SAE类型有Initial, follow-up和Summary三种，针对同一个SAE可能有时候会产生多于一条SAE report。这个可以实现么？上面的问题是不是因为已经有一个来源于AE中的Initial SAE report条目了，所以再有一个Summary 就不能识别了？
我用POD4-6来源的SAE又试了一次，好像添加过一条Initial report以后再添加另外类型的SAE，点击commit就一直显示Ongoing了。

**Comment by sunwenyuan** [comment]
我们没有这种限制， 那条ongoing是因为我们对sae报告时间的交验有错误

**Comment by sunwenyuan** [comment]
现在应该好了

**Comment by suzhang2020** [comment]
太棒了！感谢！
