### ISSUE TITLE
Principle investigator账号登陆质疑的几个问题

### ISSUE THREAD

**Issue by suzhang2020** [Yudatech/yuda-ecrf#185]
1. TSL账号登陆，密码test，这是一个principle investigator账号
2. 进入TS0003，是一个状态为committed的病例
3. 进入Preoperative screening, Demographic data，对Date of birth质疑
4. 质疑后该项目内容自动被清空
![Screen Shot 2020-09-08 at 21 30 51](https://user-images.githubusercontent.com/69921295/92520519-0380cc00-f21c-11ea-9743-0002d60f8bb0.png)

5. 用TS账号登陆，密码Test
6. 回复Date of birth这条质疑的时候出错 
![Screen Shot 2020-09-08 at 21 38 26](https://user-images.githubusercontent.com/69921295/92520547-0f6c8e00-f21c-11ea-91d3-675a6f8d9c77.png)

7. TSL登陆状态下对其他几个日期的质疑都会出现质疑commit后清空原本内容的情况，举例如下
![Screen Shot 2020-09-08 at 21 31 05](https://user-images.githubusercontent.com/69921295/92520572-1b585000-f21c-11ea-9afd-029cc8610d0e.png)
![Screen Shot 2020-09-08 at 21 31 45](https://user-images.githubusercontent.com/69921295/92520590-2317f480-f21c-11ea-8d83-996146becadf.png)

8. 内容被清空后，因为病例已经被committed了，TS大夫账户也不能重新填写，只能admin重新填（这点是正常的，就是说一下）

**Comment by suzhang2020** [comment]
目前用principle investigator账户质疑不会清空内容了，但是对日期的质疑后，再用TS账号（密码Test）回复质疑的时候会出错。请见质疑列表里对TS0003的两条质疑。
![Screen Shot 2020-09-09 at 15 42 05](https://user-images.githubusercontent.com/69921295/92606650-75582480-f2b3-11ea-9021-f99f083c6ad6.png)

**Comment by suzhang2020** [comment]
试了一下monitor账户TM，密码test，有和上述Principle investigator同样的问题

**Comment by sunwenyuan** [comment]
现在应该好了
