### ISSUE TITLE
Postoperative visit中Clavien-Dindo Classification Grade I 的AE提示需要去掉

### ISSUE THREAD

**Issue by suzhang2020** [Yudatech/yuda-ecrf#189]
进入任意病例，进入Postoperative visit，建立一个pod条目
勾选Has postoperative comlications
Clavien-Dindo Classification下拉菜单选择 Grade I 
这时候下面会弹出提示

![Screen Shot 2020-09-12 at 12 41 23](https://user-images.githubusercontent.com/69921295/92993922-19311280-f4f6-11ea-8a6d-ea7bf10a7a84.png)

能不能把针对Grade I的这个AE提示去掉？其余Grade II至IV不变？就是说Grade I不需要填写AE report。

是不是这里还有逻辑设置？可否也去掉？

**Comment by suzhang2020** [comment]
这个好像还没改过来？
![Screen Shot 2020-09-12 at 16 57 11](https://user-images.githubusercontent.com/69921295/92998313-67a3d880-f519-11ea-81d2-c20f23135d99.png)

**Comment by sunwenyuan** [comment]
现在应该好了

**Comment by suzhang2020** [comment]
太棒啦！谢谢！
