### ISSUE TITLE
文字修改和顺序修改

### ISSUE THREAD

**Issue by suzhang2020** [Yudatech/yuda-ecrf#206]
TS账号登录，密码Test
建立病例填写信息后，点击Submit，进入Submit核查页面。
文字修改请见图片。
![4](https://user-images.githubusercontent.com/69921295/93387450-8e3f7780-f869-11ea-9095-1da106d26535.jpg)
![5](https://user-images.githubusercontent.com/69921295/93387458-913a6800-f869-11ea-953a-d05710fd4d69.jpg)

另有一处顺序修改，想保持条目顺序与左侧目录栏一致，请见图片上的标注，请问可否实现？
还有一处：在Submit页面的核查条目相比左侧目录栏少了一项，即Preoperative radiotherapy，请见图片标注，请问可否加上？当然此项也可以与Preoperative radiotherapy页面新增加的下拉菜单的逻辑（必须选择Yes或者No）一起进行修改。我已在Excel表中写了下来。
谢谢！

**Comment by sunwenyuan** [comment]
还有一处：在Submit页面的核查条目相比左侧目录栏少了一项，即Preoperative radiotherapy，请见图片标注，请问可否加上？当然此项也可以与Preoperative radiotherapy页面新增加的下拉菜单的逻辑（必须选择Yes或者No）一起进行修改。我已在Excel表中写了下来。
这部分后面一起修改吧

**Comment by suzhang2020** [comment]
非常感谢，还有一个小地方需要修改一下，请见下图。
![1](https://user-images.githubusercontent.com/69921295/93464687-da320100-f8e9-11ea-9335-3f710bf131a7.jpg)

**Comment by sunwenyuan** [comment]
现在好了

**Comment by suzhang2020** [comment]
谢谢！
