### ISSUE TITLE
文字修改和顺序调整

### ISSUE THREAD

**Issue by suzhang2020** [Yudatech/yuda-ecrf#208]
登录任一病例后，文字修改，请见下图。还有两处调整一下顺序，谢谢！
![1](https://user-images.githubusercontent.com/69921295/93606859-dfb24880-f9c8-11ea-8789-e1cb1767e804.jpg)
![2](https://user-images.githubusercontent.com/69921295/93606908-efca2800-f9c8-11ea-81dd-8b7867bde3a8.jpg)
![3](https://user-images.githubusercontent.com/69921295/93606932-f48edc00-f9c8-11ea-9661-00e592803343.jpg)
![4](https://user-images.githubusercontent.com/69921295/93606939-f789cc80-f9c8-11ea-84da-c5215e5a320e.jpg)
![5](https://user-images.githubusercontent.com/69921295/93606943-f9ec2680-f9c8-11ea-8cc1-b203a754082d.jpg)
![6](https://user-images.githubusercontent.com/69921295/93606945-fc4e8080-f9c8-11ea-86fd-9d73826cb7c0.jpg)

**Comment by suzhang2020** [comment]
非常感谢！还有几个小问题，请见图片。
![1](https://user-images.githubusercontent.com/69921295/93629509-b9040a00-f9e8-11ea-8812-29387fbf6b86.jpg)

**Comment by sunwenyuan** [comment]
现在好了

**Comment by suzhang2020** [comment]
多谢多谢！
