### ISSUE TITLE
提交 - 分开返回 检验项目名称 和 检验结果，以便于style

### ISSUE THREAD

**Issue by bohua** [Yudatech/yuda-ecrf#69]

**Comment by sunwenyuan** [comment]
加css

**Comment by bohua** [comment]
返回状态除了resultText可以加一个const的值么(resultValue)？ 比如 NOT_FINISHED， FINISHED, EMPTY, ERROR...  否则多语言环境无法动态加CLASS

**Comment by sunwenyuan** [comment]
加了 resultType = 'ongoing' | 'finish' | 'empty'
