### ISSUE TITLE
首诊清单 如未全部购选， 保存后，进入commit会出错

### ISSUE THREAD

**Issue by bohua** [Yudatech/yuda-ecrf#75]
TypeError: /Users/bohua/WebstormProjects/yuda-ecrf/views/layout.pug:33
    31|                 if user.role === 'cra'
    32|                   li
  > 33|                     a.yuda-menu-btn(href="/case" class=(currentPath === '/case' ? 'active' : '')) #{buttonConfig.buttons.newpatient.text}
    34|                 li
    35|                   a.yuda-menu-btn(href="/logout") #{buttonConfig.buttons.logout.text}
    36|               else

Cannot read property 'buttons' of undefined

**Comment by sunwenyuan** [comment]
加了 resultType = 'ongoing' | 'finish' | 'empty'

**Comment by bohua** [comment]
nice
