### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by bohua** [Yudatech/yuda-ecrf#89]
1. 菜单栏中加入‘搜索’ 选项， 所有用户均可见
2. 点击后进入搜索界面
3. 界面
    a. 上方搜索条件面板， 下方搜索结果面板
    b. 搜索结果面板 上边搜索结果统计
    c. 搜索结果面板 左边病例table
    d. 搜索结果面板 右边质疑table

a. 搜索条件面板
    i. 一个input field， 按病人号， 病人姓名缩写 模糊匹配
    ii. 一个dropdown, 建档人 (CRA仅有自己，supervisor/monitor为本site的CRA, admin为全site的CRA)
    iii. 一个dropdown, 中心 (CRA／supervisor/monitor为本site, admin为全site)
    iv. 一个dropdown, 病例状态 (全部，进行中，待审核，已审核， 已完成，中途退出)
    v. 一个button, 点击进行搜索， 搜索完成后，在下方搜索结果面板内显示
    vi. 所有条件默认为空，不选择或填写则不作为搜索条件, 全都不填写，则返回此用户所有可见病例
  
b. 搜索结果面板 上边搜索结果统计
    i. 搜索到 n 条病例， n 条 对应的质疑

c. 搜索结果面板 左边病例table
   i. 默认为空
   ii. 搜索后显示匹配的病例
   iii. 结果默认以病人号升序排序
   iv. table列： 同dashboard, 操作列仅有链接按钮进入CRF表， admin有删除键

d.搜索结果面板 右边质疑table
   i. 默认为空
   ii. 搜索后显示匹配病例对应的所有质疑
   iii. 结果默认以病人号升序排序
   iv. table列： 同dashboard, 操作列仅有链接按钮进入CRF表， admin有删除键

**Comment by sunwenyuan** [comment]
getSearchConfig.js
加英文

search.pug 加CSS
