### ISSUE TITLE
排除标准 - 有任意项勾选 提示： 病人须不满足所有排除标准

### ISSUE THREAD

**Issue by bohua** [Yudatech/yuda-ecrf#94]

**Comment by sunwenyuan** [comment]
加英文 getScreeningExclusionConfig.js

**Comment by bohua** [comment]
1. 没有勾选任何项时，不要显示警告：
![image](https://user-images.githubusercontent.com/3418159/30282036-65daf4ae-9714-11e7-81e6-d93c2c9013c0.png)

2. a. 选择一项 - 出现警示，正确
    b. 再选择一项 - 警示保留，正确
    c. 去掉一项 - 警示消失，错误

![image](https://user-images.githubusercontent.com/3418159/30282134-a9773ba0-9714-11e7-980d-c421134f021a.png)
