### ISSUE TITLE
当选项为警告（黄色）时， 提示信息也应该时黄色的警示信息而不是红色错误信息

### ISSUE THREAD

**Issue by bohua** [Yudatech/yuda-ecrf#95]
1. 首诊既往史 -  心脏病， 较大腹部手术
2. 首诊合并用药 - 抗生素，抗凝血剂， 激素药物
3. 首诊体格检查 - 神清，心脏杂音
4. 复诊 - 肠道清洁， 预防性抗生素 (若使用抗生素，请完整填写《合并用药情况表》)， 预防性抗凝血药 (若使用抗凝血药，请完整填写《合并用药情况表》)
5. 手术 - 不良事件 （增加选中黄色提示： 请完整填写《不良事件及器械缺陷报告表》）
6. 首诊合并用药 - 任意项勾选后 （增加选中黄色提示：请完整填写《合并用药情况表》）
7. 访视 - 合并用药 （增加选中黄色提示：请完整填写《合并用药情况表》）
8. 访视 - 不良事件 （增加选中黄色提示：请完整填写《不良事件及器械缺陷报告表》）

**Comment by sunwenyuan** [comment]
getReviewChecklistConfig.js
getSurgeryConfig.js
getScreeningConMedConfig.js
getVisitConfig.js
加英文
