### ISSUE TITLE
首诊清单 - 未全部勾选则提示： 须符满足以上所有条件 

### ISSUE THREAD

**Issue by bohua** [Yudatech/yuda-ecrf#96]

**Comment by sunwenyuan** [comment]
加英文 getScreeningChecklistConfig.js

**Comment by bohua** [comment]
警示语句会在勾选一项后消失，应一直出现，直到所有项目勾选后消失
![image](https://user-images.githubusercontent.com/3418159/30281537-0392f5cc-9713-11e7-87a5-f9df6823ebb5.png)
![image](https://user-images.githubusercontent.com/3418159/30281555-0cad432e-9713-11e7-8139-e011ae548cac.png)

**Comment by bohua** [comment]
英文已添加
