### ISSUE TITLE
首诊 实验室检查  数据逻辑检查 没有完成

### ISSUE THREAD

**Issue by bohua** [Yudatech/yuda-ecrf#97]
![image](https://user-images.githubusercontent.com/3418159/30230119-2e3af386-94e5-11e7-9d2a-41ed82f50fe1.png)

**Comment by bohua** [comment]
皆显示为黄色警告提示

**Comment by bohua** [comment]
输入框也需要黄色警告边框

**Comment by bohua** [comment]
1. ALB 白蛋白总是有warning, 并没有<35的检验
2. ALB 白蛋有warning时，需要有额外黄色警告提示: 该结果不符合入组标准，请确认是否纳入该受试者

**Comment by sunwenyuan** [comment]
getScreeningLabConfig.js
加英文
