### ISSUE TITLE
病例概况 -  加入 审核 信息

### ISSUE THREAD

**Issue by bohua** [Yudatech/yuda-ecrf#98]
1. 签字人
   a. 试验中心负责人 (Supervisor)
   b. 试验监察员 (Monitor)
2. 签字人姓名  （supervisor, monitor的用户名）
3. 签字时间

**Comment by sunwenyuan** [comment]
getCaseOverviewConfig.js
加英文

**Comment by bohua** [comment]
1. CRA提交
2. monitor签字，病例概况中出现审核信息，正确
3. supervisor 签字， 病例概况中还是只有monitor的审核信息，而没有supervisor 的审核信息 ， 错误
